# Basic Information 
title: Alireza Taheritajar
position: PhD Student
affiliation: Augusta University
affiliation_link: https://taheritajar.net/
affiliation_logo: ./assets/img/fav.png
email: ataheritajar (at) augusta.edu

# Search Engine Optimization (SEO)
keywords: alireza taheritajar, taheritajar, augusta university
canonical: https://taheritajar.net/
description: Alireza Taheritajar is a PhD student at Augusta University. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?hl=en&user=SyK9A9EAAAAJ
github_link: https://github.com/taheritajar
linkedin: https://www.linkedin.com/in/alireza-taheri/
twitter: https://twitter.com/alireza__tht/

# Images 
avatar: https://taheritajar.net/academic/avatar.png

# Footnotes
footnote: Copyright Â© 2024 Alireza Taheritajar. Built with
footnote_link: https://github.com/taheritajar

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
